package com.mapimpress.SQLplanner.GUI;

import com.mapimpress.SQLplanner.GlobalVars;
import com.mapimpress.SQLplanner.Oracle.OraConnectionFactory;
import com.mapimpress.SQLplanner.Oracle.iConnection;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MainFrame extends JFrame {

    private final LoginDialog loginDialog;
    private final AboutDialog aboutDialog;
    private final iConnection oraConnection;
    private Connection conn;

    public MainFrame() {
        initComponents();
        loginDialog = new LoginDialog(this);
        aboutDialog = new AboutDialog(this);
        oraConnection = OraConnectionFactory.getOraConnection(OraConnectionFactory.ocType.THIN);
        setTitle("SQLplanner - Disconnected");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jpSQL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepSQL = new javax.swing.JEditorPane();
        jpPlan = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmDataBase = new javax.swing.JMenu();
        jmiConnect = new javax.swing.JMenuItem();
        jmiDisconnect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiExit = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        jmiAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jpSQL.setBorder(javax.swing.BorderFactory.createTitledBorder("SQL"));

        jepSQL.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jepSQL.setText("with\n  a as\n    (select count(j.job_id) cnt,\n            e.employee_id\n      from employees e,\n           jobs j\n      where j.job_id = e.job_id\n      group by e.employee_id)\n  \nselect a.cnt \"Jobs\",\n       e.first_name||' '||e.last_name \"Name\",\n       d.department_name \"Department\",\n       l.city \"City\",\n       c.country_name \"Country\",\n       r.region_name \"Region\"\n  from a a,\n       employees e,\n       departments d,\n       locations l,\n       countries c,\n       regions r\n  where a.employee_id = e.employee_id\n        and d.department_id = e.department_id\n        and l.location_id = d.location_id\n        and c.country_id = l.country_id\n        and r.region_id = c.region_id\n  order by r.region_name, c.country_name, d.department_name;\n");
        jepSQL.setToolTipText("Input SQL select statement");
        jScrollPane1.setViewportView(jepSQL);

        javax.swing.GroupLayout jpSQLLayout = new javax.swing.GroupLayout(jpSQL);
        jpSQL.setLayout(jpSQLLayout);
        jpSQLLayout.setHorizontalGroup(
            jpSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSQLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpSQLLayout.setVerticalGroup(
            jpSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSQLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jpSQL);

        jpPlan.setBorder(javax.swing.BorderFactory.createTitledBorder("Plan"));

        javax.swing.GroupLayout jpPlanLayout = new javax.swing.GroupLayout(jpPlan);
        jpPlan.setLayout(jpPlanLayout);
        jpPlanLayout.setHorizontalGroup(
            jpPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jpPlanLayout.setVerticalGroup(
            jpPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jpPlan);

        jMenuBar1.setFocusable(false);

        jmDataBase.setMnemonic('b');
        jmDataBase.setText("Data base");

        jmiConnect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiConnect.setMnemonic('C');
        jmiConnect.setText("Connect");
        jmiConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConnectActionPerformed(evt);
            }
        });
        jmDataBase.add(jmiConnect);

        jmiDisconnect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiDisconnect.setMnemonic('D');
        jmiDisconnect.setText("Disconnect");
        jmiDisconnect.setEnabled(false);
        jmiDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDisconnectActionPerformed(evt);
            }
        });
        jmDataBase.add(jmiDisconnect);
        jmDataBase.add(jSeparator1);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jmiExit.setMnemonic('x');
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmDataBase.add(jmiExit);

        jMenuBar1.add(jmDataBase);

        jmHelp.setMnemonic('H');
        jmHelp.setText("Help");

        jmiAbout.setMnemonic('A');
        jmiAbout.setText("About");
        jmiAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutActionPerformed(evt);
            }
        });
        jmHelp.add(jmiAbout);

        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutActionPerformed
        aboutDialog.setLocation(getLocation().x + (getWidth() - aboutDialog.getWidth()) / 2,
                                getLocation().y + (getHeight() - aboutDialog.getHeight()) / 2);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_jmiAboutActionPerformed

    private void jmiConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConnectActionPerformed
        loginDialog.setLocation(getLocation().x + (getWidth() - loginDialog.getWidth()) / 2,
                                getLocation().y + (getHeight() - loginDialog.getHeight()) / 2);
        loginDialog.SetEditors();
        loginDialog.setVisible(true);
        if (loginDialog.ModalResult.equals("OK")) {
            conn = oraConnection.Connect(GlobalVars.userName, GlobalVars.userPass, GlobalVars.oraDBName, GlobalVars.oraDBRole);
            if (conn == null) {
                JOptionPane.showMessageDialog(this, oraConnection.getLastError(), "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                jmiConnect.setEnabled(false);
                jmiDisconnect.setEnabled(true);
                setTitle("SQLplanner - Connected to database \"" + GlobalVars.oraDBName + "\" as user \"" + GlobalVars.userName + "\"");
            }
        }
    }//GEN-LAST:event_jmiConnectActionPerformed

    private void jmiDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDisconnectActionPerformed
        if (oraConnection.closeConnection()) {
            jmiConnect.setEnabled(true);
            jmiDisconnect.setEnabled(false);
            setTitle("SQLplanner - Disconnected");
        } else {
            JOptionPane.showMessageDialog(this, oraConnection.getLastError(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiDisconnectActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JEditorPane jepSQL;
    private javax.swing.JMenu jmDataBase;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiConnect;
    private javax.swing.JMenuItem jmiDisconnect;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JPanel jpPlan;
    private javax.swing.JPanel jpSQL;
    // End of variables declaration//GEN-END:variables
}
